### ISSUE TITLE
Module request: Allen & heath dlive series

### ISSUE THREAD

**Issue by Roeland22896** [bitfocus/companion-module-allenheath-dlive-ilive#1]
Hello,

I would like to request for the Allen & heath dlive series (2500).
The problem with this console seems to be that it uses Midi over TCP, they have a tcp midi driver but i don't know if that works in both ways and if you could implement the translation directly in your software. 
Any way would be nice to just control mutes from a fader/group and recall scenes (that is all control i should need),these controls are just enough to unmute audio for a movie and change between speech, video, and panel session. 

Not a priority but still fun if this would be possible.

**Comment by Sam-D03** [comment]
> Tnx for the doc's, would you be able to test some commands with a telnet session? To check formats returns etc?

Hey Jeffery! Amazing! I'm on site with a DLive C1500 today and tomorrow - and can do any tests you need!

Let me know what you need :)

**Comment by JeffreyDavidsz** [comment]
Open a connection and try the mute for example;
`9N, \x01, 7F,  9N, \x01, 00`
This is a note on for input channel 2 and off. I'm interested if these are 2 separate commands or if they can be send as 1, also if the 01 (instead of \x01) will be accepted (should be hex).
The port number to connect to is 51325

**Comment by JeffreyDavidsz** [comment]
So with a little help I pushed a small module, you'll find it in the latest release. When this works I know that the command structure is ok and add more functionality. Let me know

**Comment by matt-wadsworth** [comment]
We used this on a show a couple weeks back with this slight change to line 147 of index.js

`var channel = Integer.parseInt(opt.inputChannel);`
to
`var channel = parseInt(opt.inputChannel);`

_This is from memory so may be incorrect, fairly certain that was the change I made though._

Otherwise companion crashes/errors on sending that command to the mixer.

**Comment by JeffreyDavidsz** [comment]
All right, thanks! Meanwhile I started to rewrite some parts. After holiday I'll look into it again

**Comment by lightingman117** [comment]
> All right, thanks! Meanwhile I started to rewrite some parts. After holiday I'll look into it again

I realized I was clogging up the wrong thread. No rush, but if it would help I could setup a VM with my dLive hooked up to it so you could do testing with it while you develop. Perhaps easier than letting us test it.

Either that or a VPN to put you on the same network.

Besides that, definitely, enjoy the holiday!

**Comment by JeffreyDavidsz** [comment]
That sounds, good. I've updated the code, please test when you have time. Would love to test with a VPN, but that will require some free time first ;-)

**Comment by lightingman117** [comment]
@JeffreyDavidsz 

It works!
Index of 0 needs to change, but that's nothing.
I like that the toggle feature allows me to easily make this toggle on/off as dLive doesn't toggle it's only sent 'on/off' commands. And use case would be to toggle mute/unmute.

![companion dLive test](https://user-images.githubusercontent.com/54555519/63808333-53c50e80-c8e5-11e9-8ad3-2eb4bc721ea4.PNG)

Here's some Wireshark. Disregard the 04 vs 00 for 2nd hex value. I had the wrong channel selected in Companion.
![tcp_stream_dlive_companion_vs_packetSender](https://user-images.githubusercontent.com/54555519/63808653-12812e80-c8e6-11e9-95da-5c8a8fab8066.PNG)

**Comment by JeffreyDavidsz** [comment]
Hi thanks for testing! What do you mean with the index of 0? The list of channels starts at 1 instead of 0?

**Comment by lightingman117** [comment]
> Hi thanks for testing! What do you mean with the index of 0? The list of channels starts at 1 instead of 0?

hex value 00 = ch 1
hex value 01 = ch 2

Currently sending mute to ch1 = muting ch2

**Comment by WNTLtd** [comment]
Hey Guys - just my two pennies worth - I'm in the process of starting a native plugin for the StreamDeck to control all sorts of mixers - dLive being one of them.
Did you know, you can download their [Director software](https://www.allen-heath.com/dlive-home/software/) (for free) which emulates the desk on your desktop - so no need for the real desk to test your plugins.  One thing to note - it defaults to MIDI ch 12 - so any commands you send (not inc SysEx) will either need to be sent to ch12 or change it's midi channel to what ever you want within Director.
Oh and because it's a virtual desk running on your desktop - you need to talk to it on localhost 127.0.0.1 (obviously!)

There's a different Director app for each desk type.

So I'm wondering - why reinvent the wheel - and I might just get involved in this project.
What's the deal with Companion plugins - can anyone get involved?

**Comment by haakonnessjoen** [comment]
Anyone is free to make modules :) There are some few rules for them to be included in companion though, but nothing out of the normal. Just security based limitation, etc.

Jeffrey has already started on a module, but you are free to send pull requests to the module, and if you are more active, you might also get write access to the repo.

Sounds like it would be much better for us all, if you to co-develop this module, than to create a native plugin for streamdeck. 😀

That way, people can combine functions in (your) allen heath modules, and other equipment that companion supports in a single button, and create multi-device-"macros" of sorts.

**Comment by haakonnessjoen** [comment]
And if you are planning on making support for several mixers, that would just be awesome :)

**Comment by lightingman117** [comment]
> Hey Guys - just my two pennies worth - I'm in the process of starting a native plugin for the StreamDeck to control all sorts of mixers - dLive being one of them.
> Did you know, you can download their [Director software](https://www.allen-heath.com/dlive-home/software/) (for free) which emulates the desk on your desktop - so no need for the real desk to test your plugins. One thing to note - it defaults to MIDI ch 12 - so any commands you send (not inc SysEx) will either need to be sent to ch12 or change it's midi channel to what ever you want within Director.
> Oh and because it's a virtual desk running on your desktop - you need to talk to it on localhost 127.0.0.1 (obviously!)
> 
> There's a different Director app for each desk type.
> 
> So I'm wondering - why reinvent the wheel - and I might just get involved in this project.
> What's the deal with Companion plugins - can anyone get involved?

Did not realize you could send midi notes to Director. That's amazing, I figured it was always talking to the mixrack with its own protocols/methodology and sending midi commands to it wouldn't work.

FYI, Jeffrey I did test the above and it works properly. So you should be able to develop this fairly easily.

**Comment by lightingman117** [comment]
Jeffrey,

Any updates? Anything I can do to help?

Given that Director emulates the mixrack perfectly for midi commands makes it easy to test while developing.

**Comment by JeffreyDavidsz** [comment]
Hi @lightingman117 sorry the module got off my attention. What can I do to finish it? Id is correct now right? So adding all the channels to begin with?

**Comment by lightingman117** [comment]
Hi @JeffreyDavidsz 

No worries, we're all busy!

Yes, ID is correct!

I tested with this build: [companion-2.0.0-ee6ed6b-1845-win64.exe](https://builds.bitfocus.io/companion/)

I tested @WNTLtd suggestion and he is correct, it is very easy to download the free [offline editor](https://www.allen-heath.com/dlive-home/software/) and use the loopback 127.0.0.1 address in Companion to test ALL functionality. No dLive hardware (mixrack or surface) needed. Make sure to change the midi notes under utility > control to 1-5 instead of the default.

From the midi protocol guide: https://www.allen-heath.com/media/dLive-MIDI-TCP-Protocol-1.50.pdf

Yes, adding ID 1-128 would be a good start for muting channels.
I think the main thing I'd like to see is CH selection, Mix sends, then mutes, then scene recall.

The easy ones:
Mute functionality for all types of mutes (Channel, DCA, Mute group, Aux's, Groups, Main LR)
Scene Recall functionality.

More difficult:
Ch selection & activating mix sends.
 I need to figure out what are the correct commands as I don't think the MIDI-TCP guide has provisions for these commands. I am sure it is possible, perhaps just hidden.

**Comment by JeffreyDavidsz** [comment]
So I've moved on with this, update will be there soon. Cannot find the right command for the Sel button though

**Comment by lightingman117** [comment]
> So I've moved on with this, update will be there soon. Cannot find the right command for the Sel button though

Great, thanks for the work Jeffrey!

There isn't a Midi command for Sel or activating Mix. I am trying to trace down with Wireshark the TCP stream that performs the command, but I am not very good at this.

**Comment by lightingman117** [comment]
Very nice work!

I know you said you're still working on it, so I'm sure you already know this.

"DCA assign channel on" functions as an "off"

Sel & Mix as mentioned beforehand. But Unlikely to be a midi command to do such functions.

Will continue to try to find the correct TCP statements. I can upload Wireshark captures if it helps.

**Comment by JeffreyDavidsz** [comment]
Mmmm strange if tested again just now but on puts the DCA on....

**Comment by lightingman117** [comment]
Could be a glitch with my setup. I'll try again later tonight.

**Comment by lightingman117** [comment]
Not sure what the problem was, but it's working correctly.

I replicated my previous issue (Ch1 DCA 'ON') on a different computer, but I deleted the commands and tried a different channel and it worked properly. Went back to Ch1 and it was fixed.

---

I'd say the module is ready with the currently programmed parameters:
-Mute input
-Ch assignment to main mix
-DCA assignment
-Ch name
-Ch color
-Scene recall

I have spot-check tested all above commands) with the following setup:
CDM32 and dLive Director
V1.81 - Rev 50102
on win10 x64 laptop
wifi & hardwired
default IP


---

Expanding the mute on/off to the rest of the outputs, DCA, & mute group seems the next logical step.

---

'Sel' & 'Mix' 
Functionality seems difficult to implement due to no published spec or official method; reverse-engineering the TCP commands is proving difficult for myself, others smarter & more familiar with Wireshark than I would probably be able to accomplish this.

**Comment by kpatel3035** [comment]
Can this same module work with the Allen & Heath SQ series? I have an SQ 5 and wanted to ask before trying it out.

It seems to be similar based on the SQ-MIDI-Protocol PDF posted on their website:
https://www.allen-heath.com/media/SQ-MIDI-Protocol-Issue1.pdf

**Comment by lightingman117** [comment]
Just try it?
Can't hurt.

**Comment by JeffreyDavidsz** [comment]
Yep and let us know ;-)

**Comment by Phil0** [comment]
Hey I forked this Projekt and started adapting it for the iLive Series. https://github.com/Phil0/companion-module-allenheath-ilive

Will test it with Equipment the next week. In my first test the dLive Modules Mute worked on iLive, just the channel numbers are different.

**Comment by hlebron1** [comment]
Good morning, I am trying the companion app for the first time!  

I will be using the Ross Talk and dLive modules for the most part.

Would it be possible to Add "Volume Control" as a button option?

Volume UP & Volume down?  In the protocol manual the command is notated as: 

> Fader levels - **NRPN**

**Comment by MeestorX** [comment]
Module has been updated with additional functions.

**Comment by druidma** [comment]
> Hey I forked this Projekt and started adapting it for the iLive Series. https://github.com/Phil0/companion-module-allenheath-ilive
> 
> Will test it with Equipment the next week. In my first test the dLive Modules Mute worked on iLive, just the channel numbers are different.

Hi Phil0, 

How did you go with the iLive adaptation? I'm looking for the same thing.

Cheers
druidma

**Comment by MeestorX** [comment]
That fork is from before my update. Have you tried my updated dLive module on the iLive?

**Comment by druidma** [comment]
Hi MeestorX,
I have tried it but can't control any of the settings. The commands are not all that different to the dLive so I had hoped it'd work.

**Comment by druidma** [comment]
update, the iLive has things in a different order to the dLive. Reordering and defining the actions is the go. Now working in my test environment.

actions['mute_fx_send'] = {
			label: 'Mute FX Send',
			options: this.muteoptions('Mono FX Send', 8, -1)
		};

		actions['mute_fx_return'] = {
			label: 'Mute FX Return',
			options: this.muteoptions('Stereo FX Return', 8, 0x07)
		};

		actions['mute_dca'] = {
			label: 'Mute DCA',
			options: this.muteoptions('DCA', 16, 0x0F)
		};			
		
		actions['mute_input'] = {
			label: 'Mute Input',
			options: this.muteoptions('Input Channel', 64, 0x1F)
		};

		actions['mute_mix'] = {
			label: 'Mute Mix',
			options: this.muteoptions('Mix', 32, 0x5F)

**Comment by kimaernoudt** [comment]
Has anyone figured out the commands for aux pafl / softkeys / go(scenes) for the dlive ?
thnx!

**Comment by MeestorX** [comment]
https://discourse.checkcheckonetwo.com/t/dlive-companion-command-request-and-1-bug/2907/3?u=andy
